"""Fit the routing table from dev runs of the agent on each model.

For every task type, send it to the small model only if the small model's dev
success rate is within --margin points of the big model's. Dev has ~10 tasks per
type, so each rate is noisy: a type with fewer than --min-n dev tasks stays big.

  python scripts/fit_routing.py --big runs/dev/agent_big --small runs/dev/agent_small \
      --out agent/app/data/routing.yaml

An org crmroute was not built on gets its own table from its own dev runs:

  python scripts/fit_routing.py --org original --big runs/original_dev/full \
      --small runs/original_dev/agent_small --dev-split data/original_dev.json \
      --test-split data/original_test.json --out agent/app/data/routing_original.yaml
"""
import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).parent))
from analyze_results import CONFIDENTIALITY, expected_keys, load_system, score, validate_complete  # noqa: E402


def paired_rates(big: dict, small: dict, threshold: float) -> tuple[dict, dict]:
    """Only paired completed dev tasks may decide which model is good enough."""
    if not big or big.keys() != small.keys():
        raise ValueError("routing needs matching nonempty task sets for both models")
    validate_complete({"big": big, "small": small}, set(big))
    by_big, by_small = defaultdict(list), defaultdict(list)
    for key in sorted(big):
        task_type = big[key]["task_type"]
        by_big[task_type].append(score(big[key], threshold)[1])
        by_small[task_type].append(score(small[key], threshold)[1])
    return by_big, by_small


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--big", required=True)
    ap.add_argument("--small", required=True)
    ap.add_argument("--margin", type=float, default=2.0, help="points")
    ap.add_argument("--min-n", type=int, default=8)
    ap.add_argument("--fuzzy-threshold", type=float, default=0.5)
    ap.add_argument("--out", default="agent/app/data/routing.yaml")
    ap.add_argument("--dev-split", default="data/dev.json", type=Path)
    ap.add_argument("--test-split", default="data/test.json", type=Path)
    ap.add_argument("--org", default="", help="fit on this org's dev runs only")
    args = ap.parse_args()
    if args.min_n < 1 or not 0 <= args.margin <= 100 or not 0 <= args.fuzzy_threshold <= 1:
        ap.error("invalid sample count, margin or fuzzy threshold")
    big_rows, small_rows = load_system(Path(args.big)), load_system(Path(args.small))
    expected = expected_keys(args.dev_split)
    if args.org:
        big_rows = {k: v for k, v in big_rows.items() if k[0] == args.org}
        small_rows = {k: v for k, v in small_rows.items() if k[0] == args.org}
        expected = {k for k in expected if k[0] == args.org}
    try:
        validate_complete({"big": big_rows, "small": small_rows}, expected)
        # Split IDs must be disjoint across modes, since single/multi share tasks.
        held_out = {(org, tid) for org, _, tid in expected_keys(args.test_split)}
        if any((org, tid) in held_out for org, _, tid in big_rows):
            raise ValueError("held-out test tasks cannot be used to fit routing")
        big, small = paired_rates(big_rows, small_rows, args.fuzzy_threshold)
    except ValueError as exc:
        ap.error(str(exc))
    tiers, stats = {}, {}
    for task_type in sorted(set(big) & set(small)):
        if task_type in CONFIDENTIALITY:
            continue  # refusals are decided by the guard before routing
        b, s = big[task_type], small[task_type]
        n = min(len(b), len(s))
        b_rate, s_rate = 100 * sum(b) / len(b), 100 * sum(s) / len(s)
        tier = "small" if n >= args.min_n and s_rate >= b_rate - args.margin else "big"
        tiers[task_type] = tier
        stats[task_type] = {"n_big": len(b), "n_small": len(s), "big_pct": round(b_rate, 1), "small_pct": round(s_rate, 1)}
        print(f"{task_type:<34} big {b_rate:5.1f}% (n={len(b)})  small {s_rate:5.1f}% (n={len(s)})  -> {tier}")
    doc = {
        "default": "big",
        "margin_points": args.margin,
        "fitted_from": {"big": args.big, "small": args.small, "dev_split": args.dev_split.as_posix(),
                        "org": args.org or "all"},
        "tiers": tiers,
        "dev_stats": stats,
    }
    Path(args.out).write_text(
        "# Generated by scripts/fit_routing.py from dev runs. Do not fit on test.\n" + yaml.safe_dump(doc, sort_keys=False),
        encoding="utf-8",
    )
    print(f"{sum(t == 'small' for t in tiers.values())}/{len(tiers)} task types routed to the small model -> {args.out}")


if __name__ == "__main__":
    main()
